### ISSUE TITLE
The current copyright date is the wrong year

### ISSUE THREAD

**Issue by Zigolox** [simonthor/simonthor.github.io#5]
You could either remove the copyright notice since it isn't needed or you could change it to always display the correct year using a snippet like `new Date().toLocaleDateString("en-US").split("/")[2]` or something better using `toYear`. This is the affected [file](https://github.com/simonthor/simonthor.github.io/blob/6a98ba16ca0ad179b467338412ff0ec89a8bba0e/src/footer.jsx)

**Comment by simonthor** [comment]
This has now been fixed here: 2face8b812d46148914c22aad904435f24be6a1f. Thanks for pointing this out
